trigger:
- master

pool:
  name: 'jenkins-vm'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription (7377b726-541f-4227-a581-517cdd4dbc1d)'
    appType: 'webAppLinux'
    WebAppName: 'samplevm'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/drop/target/*.jar'
    RuntimeStack: 'TOMCAT|8.5-jre8'
    StartupCommand: 'java -cp target/jb-hello-world-maven-0.1.0.jar hello.HelloWorld'